name: mariovoltolina
favicon: null
layout_spectrum: 1
typography_spectrum: 0.6905604272615165
title: Mario Voltolina
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#dcdcdc'
    - '#aeaeae'
    - '#6a6a6a'
    - '#f9f9f9'
  brandStrength: 0.4375
  lightness: 0.03065443434752524
  saturation: 0.00825054687447846
  rhythmicContrast: 0.5
purpose: []
